CryptoEncoderDecoder/Models/CryptEncodeDecode.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CryptoEncoderDecoder.Models
{
    public class CryptEncodeDecode
    {
        public int Key { get; set; }
        public string Text { get; set; }
        public string NewText { get; set; }
        
    }
}

CryptoEncoderDecoder/Controllers/CryptController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Web.Mvc;
using CryptoEncoderDecoder.Models;
using System.Web;
using System.Linq;

namespace CryptoEncoderDecoder.Views
{
    public class CryptController : Controller
    {
        //метод для дешифровки текста
        public string GetUnCryptText(string text, int key)
        {
            string alphabet = "абвгдеёжзийклмнопрстуфхцчшщъыьэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ";
            var n = alphabet.Length;
            string outText = "";
            int u = 0;
            foreach (var textMini in text)
            {
                var isFind = false;
                for (var i = 0; i < n; i++)
                {
                    if (textMini == alphabet[i])
                    {
                        u = i;
                        isFind = true;
                        break;
                    }
                }
                if (isFind)
                {
                    var index = (u - key) % n;
                    if (index < 0) index += n;
                    outText += alphabet[index];
                }
                else
                {
                    outText += textMini;
                }
            }
            return outText;
        }
        public ActionResult CaesarDecrypt()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CaesarDecrypt(HttpPostedFileBase file, CryptEncodeDecode crypt)
        {
            ModelState.Clear();
            string inputText = crypt.Text;
            int key = crypt.Key;
            string inputTextNew = crypt.NewText;
            if (file != null && file.ContentLength > 0)
                try
                {
                    string path = Path.Combine(Server.MapPath("~/App_Data/uploads/"),
                                                Path.GetFileName(file.FileName));
                    file.SaveAs(path);
                    inputText = System.IO.File.ReadAllText(path);
                    crypt.Text = inputText;
                    ViewBag.Message = "Файл успешно был загружен!";
                }
                catch (Exception ex)
                {
                    ViewBag.Message = "Ошибка:" + ex.Message.ToString();
                }
            else
            {
                ViewBag.Message = "Файл не выбран!";
            }
            //идет перебор всех вариантов и поиск по словарю, затем подсчитывается наибольшее количество совпадений слов в словаре, после чего этот вариант текста выводится 
            var fileText = System.IO.File.ReadAllLines(Server.MapPath("~/App_Data/uploads/vocabulary.txt"));
            List<string> str = new List<string>();
            Dictionary<int, string> dic = new Dictionary<int, string>();
            string[] strings = new string[33];
            var LogHashSet = new HashSet<string>(fileText);

            for (int i = 1; i < 33; i++)
            {
                str.Add(GetUnCryptText(inputText, i));
            }
            foreach (var item in str)
            {
                int count = 0;
                strings = item.Split(' ');
                for (int i = 0; i < strings.Length; i++)
                {
                    if (LogHashSet.Contains(strings[i]))
                    { count++; }
                }
                if (!dic.Keys.Contains(count))
                {
                    dic.Add(count, item);
                }
            }
            inputTextNew = dic.FirstOrDefault(x => x.Key == dic.Keys.Max()).Value;
            crypt.NewText = inputTextNew;
            return View("CaesarDecrypt", crypt);
        }

    
        public ActionResult CaesarCrypt()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CaesarCrypt(CryptEncodeDecode crypt)
        {
            ModelState.Clear();
            int key = crypt.Key;
            string inputText = crypt.Text;
            string inputTextNew = crypt.NewText;
            //шифрует текст
            string alphabet = "абвгдеёжзийклмнопрстуфхцчшщъыьэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ";
            var n = alphabet.Length;
            int u = 0;
            foreach (var inputTextMini in inputText)
            {
                var isFind = false;
                for (var i = 0; i < n; i++)
                {
                    if (inputTextMini == alphabet[i])
                    {
                        u = i;
                        isFind = true;
                        break;
                    }
                }
                if (isFind)
                {
                    inputTextNew += alphabet[(u + key) % n];
                }
                else
                {
                    inputTextNew += inputTextMini;
                }
            }
            crypt.NewText = inputTextNew;
            return View("CaesarCrypt", crypt);
        }
    }
}

CryptoEncoderDecoder/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CryptoEncoderDecoder.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {          
            return View();
        }

        
    }
}

CryptoEncoderDecoder/Views/Crypt/CaesarCrypt.cshtml
@model CryptoEncoderDecoder.Models.CryptEncodeDecode

@{
    ViewBag.Title = "Шифрование";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="text-align: center;">Шифрование</h2>

@using (Html.BeginForm("CaesarCrypt", "Crypt", FormMethod.Post))
{
    <table cellpadding="0" cellspacing="0">

        <tr>
            <td>Текст: </td>
            <td>
                @Html.TextAreaFor(m => m.Text, new { @class = "form-control", rows = "7" })
            </td>
        </tr>
        <tr>
            <td>Ключ: </td>
            <td>
                @Html.TextBoxFor(m => m.Key, new { @class = "form-control", rows = "2" })
            </td>
        </tr>
        <tr>
            <td>Зашифрованный текст: </td>
            <td>

                @Html.TextAreaFor(m => m.NewText, new { @class = "form-control", rows = "7", id="textbox" })
            </td>
        <tr>

        <tr>
            <td><br /></td>
            <td>
                <br />
                <input type="submit" value="Зашифровать" class="btn btn-primary btn-lg" />
                <button class="btn btn-primary btn-lg" id="createFile">Сохранить в файл</button>
            </td>
        </tr>
    </table>

}
@section scripts{
    <script type="text/javascript">
        (function () {
            var textFile = null,
                makeTextFile = function (text) {
                    var data = new Blob([text], { type: 'text/plain' });
                    if (textFile !== null) {
                        window.URL.revokeObjectURL(textFile);
                    }
                    textFile = window.URL.createObjectURL(data);
                    return textFile;
                };
            var create = document.getElementById('createFile'),
                textbox = document.getElementById('textbox');

            create.addEventListener('click', function () {
                var link = document.createElement('a');
                link.setAttribute('download', 'crypt_text.txt');
                link.href = makeTextFile(textbox.value);
                document.body.appendChild(link);
                window.requestAnimationFrame(function () {
                    var event = new MouseEvent('click');
                    link.dispatchEvent(event);
                    document.body.removeChild(link);
                });

            }, false);
        })();

</script>
    }

CryptoEncoderDecoder/Views/Crypt/CaesarDecrypt.cshtml
@model CryptoEncoderDecoder.Models.CryptEncodeDecode

@{
    ViewBag.Title = "Дешифрование";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="text-align: center;">Дешифрование</h2>
@using (Html.BeginForm("CaesarDecrypt",
                        "Crypt",
                        FormMethod.Post,
                        new { enctype = "multipart/form-data" }))
{
    <table cellpadding="0" cellspacing="0">

        <tr>
            <td><input type="file" name="file" id="file" accept=".txt" />  <br /></td>
            <td><input type="submit" class="btn btn-primary btn-lg" value="Загрузить" />
                      <button class="btn btn-primary btn-lg" id="createFile">Сохранить в файл</button>
            <br />
            </td>            
        </tr>
        <tr></tr>
        <tr>
            <td><br />Зашифрованный текст: </td>
            <td><br />
                @Html.TextAreaFor(m => m.Text, new { @class = "form-control", rows = "8" })
            </td>
        <tr>
        <tr>
            <td>Расшифрованный текст: </td>
            <td>
                @Html.TextAreaFor(m => m.NewText, new { @class = "form-control", rows = "8", id = "textbox" })
            </td>
        <tr>
            @ViewBag.Message
    </table>}

@section scripts{
    <script type="text/javascript">
        (function () {
            var textFile = null,
                makeTextFile = function (text) {
                    var data = new Blob([text], { type: 'text/plain' });
                    if (textFile !== null) {
                        window.URL.revokeObjectURL(textFile);
                    }
                    textFile = window.URL.createObjectURL(data);
                    return textFile;
                };
            var create = document.getElementById('createFile'),
                textbox = document.getElementById('textbox');

            create.addEventListener('click', function () {
                var link = document.createElement('a');
                link.setAttribute('download', 'decrypt_text.txt');
                link.href = makeTextFile(textbox.value);
                document.body.appendChild(link);
                window.requestAnimationFrame(function () {
                    var event = new MouseEvent('click');
                    link.dispatchEvent(event);
                    document.body.removeChild(link);
                });

            }, false);
        })();

    </script>
}

CryptoEncoderDecoder/Views/Home/About.cshtml
@{
    ViewBag.Title = "Информация о шифре Цезаря";
}
<h2>@ViewBag.Title.</h2>

<p>Шифр Цезаря, также известный как шифр сдвига, код Цезаря или сдвиг Цезаря — один из самых простых и наиболее широко известных методов шифрования.</p>
<p>Шифр Цезаря — это вид шифра подстановки, в котором каждый символ в открытом тексте заменяется символом, находящимся на некотором постоянном числе позиций левее или правее него в алфавите. Например, в шифре со сдвигом вправо на 3, А была бы заменена на Г, Б станет Д, и так далее.</p>
<p>Шифр назван в честь римского полководца Гая Юлия Цезаря, использовавшего его для секретной переписки со своими генералами.</p>
<p>Шаг шифрования, выполняемый шифром Цезаря, часто включается как часть более сложных схем, таких как шифр Виженера, и всё ещё имеет современное приложение в системе ROT13. Как и все моноалфавитные шифры, шифр Цезаря легко взламывается и не имеет почти никакого применения на практике.</p>